name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - name: analyze
        run: |
          cd example
          flutter pub get
          cd ..
          flutter analyze . example
      - name: Build (Linux)
        run: |
          sudo apt-get update -y && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
          flutter config --enable-linux-desktop
          cd example
          flutter create --platforms=linux .
          flutter build linux
        if: matrix.os == 'ubuntu-latest'
      # - name: Build (Windows)
      #   run: |
      #     flutter config --enable-windows-desktop
      #     cd example
      #     flutter create --platforms=windows .
      #     flutter doctor
      #     flutter build windows
      #   if: matrix.os == 'windows-latest'
